{
 "title": "Viewer",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "min_viewer", "label": "Minimum viewer", "query": "1000" },
   {
    "name": "channel",
    "label": "Channel",
    "query": "SELECT user_name FROM stream_records WHERE $__timeFilter(created_at) AND viewer_count > $min_viewer;"
   }
  ]
 },
 "panels": [
  {
   "title": "current viewer",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT created_at AS \"time\",\n  user_name AS \"user_name\",\n  avg(viewer_count) OVER (\n    PARTITION BY user_name\n    ORDER BY created_at ROWS 5 PRECEDING\n  ) AS \"viewer_count\"\nFROM stream_records\nWHERE $__timeFilter(created_at)\n  AND user_name IN($channel)\n  AND viewer_count > $min_viewer\nORDER BY 1,\n  2"
    }
   ]
  },
  {
   "title": "Total viewer by game",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(created_at, $__interval),\n  game_name AS metric,\n  avg(sum(viewer_count)) OVER (\n    PARTITION BY game_name\n    ORDER BY $__timeGroup(created_at, $__interval) ROWS 5 PRECEDING\n  ) AS \"viewer_count\"\nFROM stream_records\nWHERE $__timeFilter(created_at)\n  AND user_name IN ($channel)\n  AND viewer_count > $min_viewer\nGROUP BY 1,\n  game_name,\n  2\nORDER BY 1,\n  2"
    }
   ]
  },
  {
   "title": "Viewer Change",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(created_at, 5m),\n  user_name AS metric,\n  avg(viewer_count) - lag(avg(viewer_count)) OVER (\n    PARTITION BY user_name\n    ORDER BY $__timeGroup(created_at, 5m)\n  ) AS \"viewer_count\"\nFROM stream_records\nWHERE $__timeFilter(created_at)\n  AND user_name IN ($channel)\n  AND viewer_count > $min_viewer\nGROUP BY 1,\n  2\nORDER BY 1,\n  2"
    }
   ]
  },
  {
   "title": "Follower Change",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT $__timeGroupAlias(created_at, 5m),\n  user_name AS metric,\n  avg(follower_count) - lag(avg(follower_count)) OVER (\n    PARTITION BY user_name\n    ORDER BY $__timeGroup(created_at, 5m)\n  ) AS \"follower_delta\"\nFROM stream_records\nWHERE $__timeFilter(created_at)\n  AND user_name IN ($channel)\n  AND viewer_count > $min_viewer\nGROUP BY 1,\n  2\nORDER BY 1,\n  2"
    }
   ]
  }
 ]
}